name: 'Plan Azure'

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  Terraform:
    uses: perrness/reusable-workflows/.github/workflows/azure-plan.yaml@main
    with:
      terraform_args: >-
        -var-file="repos.tfvars"
    secrets: inherit
