name: 'Plan Azure'

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  Terraform:
    uses: perrness/reusable-workflows/.github/workflows/azure-plan.yaml@input_args
    with:
      terraform_args: >-
        -var-file="repos.tfvars" -var="kv_name=${{ secrets.KV_NAME }}" -var="rg_kv_name=${{ secrets.RG_KV_NAME }}"
    secrets: inherit
