name: 'Plan Azure'

on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  Terraform:
    uses: perrness/reusable-workflows/.github/workflows/azure-plan.yaml@input_args
    env:
      KV_NAME: ${{ secrets.KV_NAME }}
      RG_KV_NAME: ${{ secrets.RG_KV_NAME }}
    with:
      terraform_args: >-
        -var-file="repos.tfvars" -var="kv_name=$KV_NAME" -var="rg_kv_name=$RG_KV_NAME"
    secrets: inherit
